export const GET_MY_ACCOUNTS_REQUESTED = 'GET_MY_ACCOUNTS_REQUESTED';
export const GET_MY_ACCOUNTS_SUCCESS = 'GET_MY_ACCOUNTS_SUCCESS';
export const GET_MY_ACCOUNTS_FAILED = 'GET_MY_ACCOUNTS_FAILED';

export const GET_ALL_ACCOUNTS_REQUESTED = 'GET_ALL_ACCOUNTS_REQUESTED';
export const GET_ALL_ACCOUNTS_SUCCESS = 'GET_ALL_ACCOUNTS_SUCCESS';
export const GET_ALL_ACCOUNTS_FAILED = 'GET_ALL_ACCOUNTS_FAILED';

export const GET_REQUESTS_REQUESTED = 'GET_REQUESTS_REQUESTED';
export const GET_REQUESTS_SUCCESS = 'GET_REQUESTS_SUCCESS';
export const GET_REQUESTS_FAILED = 'GET_REQUESTS_FAILED';

export const GET_SINGLE_ACCOUNT_REQUESTED = 'GET_SINGLE_ACCOUNT_REQUESTED';
export const GET_SINGLE_ACCOUNT_SUCCESS = 'GET_SINGLE_ACCOUNT_SUCCESS';
export const GET_SINGLE_ACCOUNT_FAILED = 'GET_SINGLE_ACCOUNT_FAILED';

export const ADD_CLIENT_ACCOUNT_REQUESTED = 'ADD_CLIENT_ACCOUNT_REQUESTED';
export const ADD_CLIENT_ACCOUNT_SUCCESS = 'ADD_CLIENT_ACCOUNT_SUCCESS';
export const ADD_CLIENT_ACCOUNT_FAILED = 'ADD_CLIENT_ACCOUNT_FAILED';

export const UPDATE_CLIENT_ACCOUNT_REQUESTED = 'UPDATE_CLIENT_ACCOUNT_REQUESTED';
export const UPDATE_CLIENT_ACCOUNT_SUCCESS = 'UPDATE_CLIENT_ACCOUNT_SUCCESS';
export const UPDATE_CLIENT_ACCOUNT_FAILED = 'UPDATE_CLIENT_ACCOUNT_FAILED';

export const GET_PLACEMENTS_REQUESTED = 'GET_PLACEMENTS_REQUESTED';
export const GET_PLACEMENTS_SUCCESS = 'GET_PLACEMENTS_SUCCESS';
export const GET_PLACEMENTS_FAILED = 'GET_PLACEMENTS_FAILED';

export const ADD_PLACEMENT_REQUESTED = 'ADD_PLACEMENT_REQUESTED';
export const ADD_PLACEMENT_SUCCESS = 'ADD_PLACEMENT_SUCCESS';
export const ADD_PLACEMENT_FAILED = 'ADD_PLACEMENT_FAILED';

export const UPDATE_PLACEMENT_REQUESTED = 'UPDATE_PLACEMENT_REQUESTED';
export const UPDATE_PLACEMENT_SUCCESS = 'UPDATE_PLACEMENT_SUCCESS';
export const UPDATE_PLACEMENT_FAILED = 'UPDATE_PLACEMENT_FAILED';
