export const GET_ACCOUNTS_REQUESTED = 'GET_ACCOUNTS_REQUESTED';
export const GET_ACCOUNTS_SUCCESS = 'GET_ACCOUNTS_SUCCESS';
export const GET_ACCOUNTS_FAILED = 'GET_ACCOUNTS_FAILED';

export const ADD_ACCOUNT_REQUESTED = 'ADD_ACCOUNT_REQUESTED';
export const ADD_ACCOUNT_SUCCESS = 'ADD_ACCOUNT_SUCCESS';
export const ADD_ACCOUNT_FAILED = 'ADD_ACCOUNT_FAILED';

export const UPDATE_ACCOUNT_REQUESTED = 'UPDATE_ACCOUNT_REQUESTED';
export const UPDATE_ACCOUNT_SUCCESS = 'UPDATE_ACCOUNT_SUCCESS';
export const UPDATE_ACCOUNT_FAILED = 'UPDATE_ACCOUNT_FAILED';

export const GET_PLACEMENTS_REQUESTED = 'GET_PLACEMENTS_REQUESTED';
export const GET_PLACEMENTS_SUCCESS = 'GET_PLACEMENTS_SUCCESS';
export const GET_PLACEMENTS_FAILED = 'GET_PLACEMENTS_FAILED';

export const ADD_PLACEMENT_REQUESTED = 'ADD_PLACEMENT_REQUESTED';
export const ADD_PLACEMENT_SUCCESS = 'ADD_PLACEMENT_SUCCESS';
export const ADD_PLACEMENT_FAILED = 'ADD_PLACEMENT_FAILED';

export const UPDATE_PLACEMENT_REQUESTED = 'UPDATE_PLACEMENT_REQUESTED';
export const UPDATE_PLACEMENT_SUCCESS = 'UPDATE_PLACEMENT_SUCCESS';
export const UPDATE_PLACEMENT_FAILED = 'UPDATE_PLACEMENT_FAILED';
