export const GET_ACCOUNTS_REQUESTED = 'GET_ACCOUNTS_REQUESTED';
export const GET_ACCOUNTS_SUCCESS = 'GET_ACCOUNTS_SUCCESS';
export const GET_ACCOUNTS_FAILED = 'GET_ACCOUNTS_FAILED';

export const ADD_ACCOUNT_REQUESTED = 'ADD_ACCOUNT_REQUESTED';
export const ADD_ACCOUNT_SUCCESS = 'ADD_ACCOUNT_SUCCESS';
export const ADD_ACCOUNT_FAILED = 'ADD_ACCOUNT_FAILED';

export const UPDATE_ACCOUNT_REQUESTED = 'UPDATE_ACCOUNT_REQUESTED';
export const UPDATE_ACCOUNT_SUCCESS = 'UPDATE_ACCOUNT_SUCCESS';
export const UPDATE_ACCOUNT_FAILED = 'UPDATE_ACCOUNT_FAILED';
